### ISSUE TITLE
Unable to add images, front or backend

### ISSUE THREAD

**Issue by ghyphtedhippie** [stepan1010/memeone#6]
Hello, 
I know this hasn't been touched in a while, but I'm hopeful. Here is my issue. I can't add any pictures, front or back.

Error:

Error Details
=============
An error of type E_ERROR was caused in line 243 of the file /home/noose/public_html/wp-content/plugins/memeone/memeone-admin-backgrounds.php. Error message: Uncaught Error: Call to undefined function mysql_real_escape_string() in /home/noose/public_html/wp-content/plugins/memeone/memeone-admin-backgrounds.php:243
Stack trace:
#0 /home/noose/public_html/wp-content/plugins/memeone/memeone-admin-backgrounds.php(67): memeone_save_new_background(Resource id #68, 'BClinton1', '1')
#1 /home/noose/public_html/wp-content/plugins/memeone/memeone.php(699): include('/home/noose/pub...')
#2 /home/noose/public_html/wp-includes/class-wp-hook.php(288): memeone_include_admin_backgrounds_page('')
#3 /home/noose/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#4 /home/noose/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#5 /home/noose/public_html/wp-admin/admin.php(254): do_action('memeone_page_me...')
#6 {main}
  thrown

The site is epsteinsnoose.com and click on Meme Maker
Any info would be really helpful!
Thanks

**Comment by ghyphtedhippie** [comment]
Solved this by literally deleting the mysql_real_escape_string from all files in which it is present. Just that exact string. Nothing else.
